myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'myapp'

urlpatterns = [
    path('', views.index),
    path('products/', views.products),
    path('products/<int:id>/', views.product_detail, name='product_detail'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/update/<int:id>', views.update_product, name='update_product')
]

myproject/urls.py
from xml.dom.minidom import Document
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=300)
    image = models.ImageField(blank=True, upload_to='images')

myapp/views.py
import re
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
# Create your views here.

def index(request):
    return HttpResponse("Hello America!")

def products(request):
    context = {
        'products':Product.objects.all()
    }
    return render(request, 'index.html', context)

def product_detail(request, id):
    context = {
        'product':Product.objects.get(id=id)
    }
    return render(request, 'detail.html', context)

def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        product = Product(name=name, price=price, desc=desc)
        product.save()
    return render(request, 'addproduct.html')

def update_product(request, id):
    context = {
        'product': Product.objects.get(id=id)
    }
    return render(request, 'updateproduct.html')

templates/addproduct.html
<form method="POST">
    {% csrf_token %}
    <input placeholder="Name" type="text", name="name", id="name">
    <input placeholder="Price" type="text", name="price", id="price">
    <input placeholder="Description" type="text", name="desc", id="desc">
    <input type="submit" name ="Add product" value = "Add Product">
</form>

templates/base.html
{%load static%}

<htnl>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    </head>
    <body>
        <nav class="bg-white shadow-lg">
            <div class="max-w-6xl mx-auto">
                <div class="flex justify-between">
                    <div class="flex space-x-7">
                        <div> 
                            <a href="#" class="flex items-center px-2 py-4">
                            <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png '%}" alt="">
                            <span class="text-gray-500 font-semibold text-lg">Buy&Sell</span>
                        </a>
                        </div>
                        <div class="items-center flex space-x-1">
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                            <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contact</a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>      
        
        {% block body %}

        {% endblock %}
    </body>
</htnl>

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<h1>{{product.name}}</h1>
<h2>{{product.price}}</h2>
<h3>{{product.desc}}</h3>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
        
        <main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
                <div class="sm:text-center lg:text-left">
                        <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl  md:text-6xl">
                                <span class="block xl:inline ">Premium Products</span>
                                <span class="block text-green-500 xl:inline">Non-premium Prices</span>
                        </h1>
                        <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0"> 
                                Get the best quality used products across the Kazakhstan. Free shipping.
                        </p>
                </div>
        </main>

        {% for p in products %}

        <a href="{% url 'myapp:product_detail' p.id  %}">
           {{p.name}}   {{p.price}}   {{p.desc}}
           <img src="{{product.image.url}}" alt="">
        </a>

        {% endfor %}

{% endblock %}

templates/updateproduct.html
<form method="POST">
    {% csrf_token %}
    <input placeholder="Name" value="{{product.name}}" type="text", name="name", id="name">
    <input placeholder="Price" type="text", name="price", id="price" value="{{product.price}}">
    <input placeholder="Description" type="text", name="desc", id="desc" value="{{product.desc}}">
    <input type="submit" name ="Add product" value = "Add Product">
</form>